version: "3.8"
services:
  chroma:
    image: chromadb/chroma
    ports:
      - "8001:8000"
    environment:
      - IS_PERSISTENT=TRUE
    volumes:
      - chroma_data:/chroma/.chroma/index

  rag-app:
    build: ./src
    depends_on:
      - chroma
    environment:
      - HF_TOKEN=${HF_TOKEN}
      - PERSIST_DIRECTORY=/app/chroma_db
      - EMBEDDING_MODEL=sentence-transformers/all-MiniLM-L6-v2
      - LLM_MODEL=google/flan-t5-base
      - CHROMA_HOST=http://chroma:8000
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app

volumes:
  chroma_data: