
version: "3.10"
services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: chroma_db
    ports:
    - "8080:8080"
    environment:
    - ALLOW_RESET=true
    volumes:
    - ./chroma_data:/chroma/.chromadb


  rag_app:
    build: .
    container_name: rag_app
    env_file: .env
    ports:
    - "8000:8000"
    depends_on:
    - chromadb
    environment:
    - HF_TOKEN=${HF_TOKEN}
    - CHROMA_HOST=${CHROMA_HOST}
    - ENABLE_GENERATION=true
    # volumes:
    # - ./app:/app 
